#!/bin/sh

if [ -z "$1" ]; then
    echo "delete_user [username]"
    exit 1
fi

echo "Fetching apache2-utils for htpasswd .."
apk add --no-cache --update apache2-utils

htpasswd -D $PASSWORD_FILE $1
