name: 'Dockerfiles'
on:
  push:
  schedule:
  - cron: 0 8 * * *
jobs:
  build_dockerfiles:
    name: build_dockerfiles
    runs-on: ubuntu-latest
    steps:

    - name: login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL

    # https://github.com/actions/checkout
    - uses: actions/checkout@master

    - name: install curl and jq
      run: |
        sudo apt-get update && sudo apt-get -y install curl jq

    - name: get latest version for go-httpbin-arm
      run: |
        ./go-httpbin-arm/getLatestGoHttpBin2Release.sh HEAD

    - name: get latest version for perkeep-arm
      run: |
        ./perkeep-arm/getLatestPerkeepCommit.sh HEAD

    - name: get latest version for lego-arm
      run: |
        ./lego-arm/getLatestLego2Release.sh linux arm64 latest

    - name: get latest version for rest-server-arm
      run: |
        ./rest-server-arm/getLatestRestServer2Release.sh linux armv7 latest

    - name: get latest version for armv6 prometheus
      run: |
        ./prometheus-arm/getLatestPrometheus2Release.sh linux armv6 latest

    - name: get latest version for armv6 alertmanager
      run: |
        ./alertmanager-arm/getLatestAlertManager.sh linux armv6 latest

    - name: get latest version for armv6 blackbox_exporter
      run: |
        ./blackbox_exporter-arm/getLatestBlackBoxExporter2Release.sh linux armv6 latest

    - name: build image and push for go-httpbin-arm
      run: |
        docker buildx build --platform=linux/arm64 --push \
        -t keyglitch/go-httpbin-arm:latest -t keyglitch/go-httpbin-arm:$(cat /home/runner/work/Dockerfiles/Dockerfiles/go-httpbin-arm/VERSION) \
        -f /home/runner/work/Dockerfiles/Dockerfiles/go-httpbin-arm/Dockerfile .

    - name: build image and push for perkeep-arm
      run: |
        docker buildx build --platform=linux/arm64 --push \
        -t keyglitch/perkeep-arm:latest -t keyglitch/perkeep-arm:$(cat /home/runner/work/Dockerfiles/Dockerfiles/perkeep-arm/VERSION) \
        -f /home/runner/work/Dockerfiles/Dockerfiles/perkeep-arm/Dockerfile .

    - name: build image and push for lego-arm
      run: |
        docker buildx build --platform=linux/arm64 --push \
        -t keyglitch/lego-arm:latest -t keyglitch/lego-arm:$(cat /home/runner/work/Dockerfiles/Dockerfiles/lego-arm/VERSION) \
        -f /home/runner/work/Dockerfiles/Dockerfiles/lego-arm/Dockerfile .

    - name: build image and push for arm rest-server-arm
      run: |
        docker buildx build --platform=linux/arm64 --push \
        -t keyglitch/rest-server-arm:latest -t keyglitch/rest-server-arm:$(cat /home/runner/work/Dockerfiles/Dockerfiles/rest-server-arm/VERSION) \
        -f /home/runner/work/Dockerfiles/Dockerfiles/rest-server-arm/Dockerfile .

    - name: build image and push for armv6 prometheus
      run: |
        docker buildx build --platform=linux/arm64 --push \
        -t keyglitch/prometheus:latest -t keyglitch/prometheus:$(cat /home/runner/work/Dockerfiles/Dockerfiles/prometheus/VERSION) \
        -f /home/runner/work/Dockerfiles/Dockerfiles/prometheus/Dockerfile .

    - name: build image and push for armv6 alertmanager
      run: |
        docker buildx build --platform=linux/arm64 --push \
        -t keyglitch/alertmanager:latest -t keyglitch/alertmanager:$(cat /home/runner/work/Dockerfiles/Dockerfiles/alertmanager/VERSION) \
        -f /home/runner/work/Dockerfiles/Dockerfiles/alertmanager/Dockerfile .

    - name: build image and push for armv6 blackbox_exporter
      run: |
        docker buildx build --platform=linux/arm64 --push \
        -t keyglitch/blackbox_exporter:latest -t keyglitch/blackbox_exporter:$(cat /home/runner/work/Dockerfiles/Dockerfiles/blackbox_exporter/VERSION) \
        -f /home/runner/work/Dockerfiles/Dockerfiles/blackbox_exporter/Dockerfile .

    - name: build image and push for f3.dockerfile
      run: |
        docker build -t keyglitch/f3 -f f3/f3.dockerfile . && \
        docker push keyglitch/f3
