name: 'Dockerfiles'
on:
  push:
  schedule:
  - cron: 0 8 * * *
jobs:
  build_dockerfiles:
    name: build_dockerfiles
    runs-on: ubuntu-latest
    steps:

    - name: login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL

    # https://github.com/actions/checkout
    - uses: actions/checkout@master

    - name: install curl and jq
      run: |
        sudo apt-get update && sudo apt-get -y install curl jq

    - name: get latest version for go-httpbin-arm
      run: |
        ./go-httpbin-arm/getLatestGoHttpBin2Release.sh HEAD
          
    - name: get latest version for perkeep-arm
      run: |
        ./perkeep-arm/getLatestPerkeepCommit.sh HEAD
          
    - name: get latest version for minio-arm
      run: |
        ./minio-arm/getLatestMinio2Release.sh latest
          
    - name: get latest version for lego-arm
      run: |
        ./lego-arm/getLatestLego2Release.sh linux armv7 latest
          
    - name: get latest version for rest-server-arm
      run: |
        ./rest-server-arm/getLatestRestServer2Release.sh linux arm latest && cp -a ./rest-server-arm/docker $PWD
          
    - name: get latest version for armv6 prometheus
      run: |
        ./prometheus-arm/getLatestPrometheus2Release.sh linux armv6 latest
          
    - name: get latest version for armv6 alertmanager
      run: |
        ./alertmanager-arm/getLatestAlertManager.sh linux armv6 latest
          
    - name: get latest version for armv6 blackbox_exporter
      run: |
        ./blackbox_exporter-arm/getLatestBlackBoxExporter2Release.sh linux armv6 latest
          
    - name: build image and push for go-httpbin-arm
      run: |
        docker build -t keyglitch/go-httpbin-arm:latest -f /home/runner/work/Dockerfiles/Dockerfiles/go-httpbin-arm/Dockerfile . && \
        docker tag keyglitch/go-httpbin-arm:latest keyglitch/go-httpbin-arm:$(cat /home/runner/work/Dockerfiles/Dockerfiles/go-httpbin-arm/VERSION) && \
        docker push keyglitch/go-httpbin-arm
          
    - name: build image and push for perkeep-arm
      run: |
        docker build -t keyglitch/perkeep-arm:latest -f /home/runner/work/Dockerfiles/Dockerfiles/perkeep-arm/Dockerfile . && \
        docker tag keyglitch/perkeep-arm:latest keyglitch/perkeep-arm:$(cat /home/runner/work/Dockerfiles/Dockerfiles/perkeep-arm/VERSION) && \
        docker push keyglitch/perkeep-arm
          
    - name: build image and push for arm minio-arm
      run: |
        docker build -t keyglitch/minio-arm:latest -f /home/runner/work/Dockerfiles/Dockerfiles/minio-arm/Dockerfile . && \
        docker tag keyglitch/minio-arm:latest keyglitch/minio-arm:$(cat /home/runner/work/Dockerfiles/Dockerfiles/minio-arm/VERSION) && \
        docker push keyglitch/minio-arm
          
    - name: build image and push for lego-arm
      run: |
        docker build -t keyglitch/lego-arm:latest -f /home/runner/work/Dockerfiles/Dockerfiles/lego-arm/Dockerfile . && \
        docker tag keyglitch/lego-arm:latest keyglitch/lego-arm:$(cat /home/runner/work/Dockerfiles/Dockerfiles/lego-arm/VERSION) && \
        docker push keyglitch/lego-arm
          
    - name: build image and push for arm rest-server-arm
      run: |
        docker build -t keyglitch/rest-server-arm:latest -f /home/runner/work/Dockerfiles/Dockerfiles/rest-server-arm/Dockerfile . && \
        docker tag keyglitch/rest-server-arm:latest keyglitch/rest-server-arm:$(cat /home/runner/work/Dockerfiles/Dockerfiles/rest-server-arm/VERSION) && \
        docker push keyglitch/rest-server-arm
          
    - name: build image and push for armv6 prometheus
      run: |
        docker build -t keyglitch/prometheus:latest -f /home/runner/work/Dockerfiles/Dockerfiles/prometheus/Dockerfile . && \
        docker tag keyglitch/prometheus:latest keyglitch/prometheus:$(cat /home/runner/work/Dockerfiles/Dockerfiles/prometheus/VERSION) && \
        docker push keyglitch/prometheus
          
    - name: build image and push for armv6 alertmanager
      run: |
        docker build -t keyglitch/alertmanager:latest -f /home/runner/work/Dockerfiles/Dockerfiles/alertmanager/Dockerfile . && \
        docker tag keyglitch/alertmanager:latest keyglitch/alertmanager:$(cat /home/runner/work/Dockerfiles/Dockerfiles/alertmanager/VERSION) && \
        docker push keyglitch/alertmanager
          
    - name: build image and push for armv6 blackbox_exporter
      run: |
        docker build -t keyglitch/blackbox_exporter:latest -f /home/runner/work/Dockerfiles/Dockerfiles/blackbox_exporter/Dockerfile . && \
        docker tag keyglitch/blackbox_exporter:latest keyglitch/blackbox_exporter:$(cat /home/runner/work/Dockerfiles/Dockerfiles/blackbox_exporter/VERSION) && \
        docker push keyglitch/blackbox_exporter
          
    - name: build image and push for f3.dockerfile
      run: |
        docker build -t keyglitch/f3 -f f3/f3.dockerfile . && docker push keyglitch/f3
