name: 'Dockerfiles'
on:
  schedule:
  - cron: 0 8 * * *
jobs:
  build_dockerfiles:
    name: build_dockerfiles
    runs-on: ubuntu-latest
    steps:

    - name: login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL

    # https://github.com/actions/checkout
    - uses: actions/checkout@master
    
    - name: latest go-httpbin-arm
      run: |
        apt-get update && apt-get -y install curl jq && ./go-httpbin-arm/getLatestGoHttpBin2Release.sh HEAD
          
    - name: latest perkeep-arm
      run: |
        apt-get update && apt-get -y install curl jq && ./perkeep-arm/getLatestPerkeepCommit.sh HEAD
          
    - name: latest minio-arm
      run: |
        apt-get update && apt-get -y install curl jq && ./minio-arm/getLatestMinio2Release.sh latest
          
    - name: latest lego-arm
      run: |
        apt-get update && apt-get -y install curl jq && ./lego-arm/getLatestLego2Release.sh linux armv7 latest
          
    - name: latest rest-server-arm
      run: |
        apt-get update && apt-get -y install curl jq && ./rest-server-arm/getLatestRestServer2Release.sh linux arm latest && cp -a ./rest-server-arm/docker $PWD
          
    - name: latest armv6 prometheus
      run: |
        apt-get update && apt-get -y install curl jq && ./prometheus-arm/getLatestPrometheus2Release.sh linux armv6 latest
          
    - name: latest armv6 alertmanager
      run: |
        apt-get update && apt-get -y install curl jq && ./alertmanager-arm/getLatestAlertManager.sh linux armv6 latest
          
    - name: latest armv6 blackbox_exporter
      run: | 
        apt-get update && apt-get -y install curl jq && ./blackbox_exporter-arm/getLatestBlackBoxExporter2Release.sh linux armv6 latest
          
    - name: buildpush go-httpbin-arm
      run: |
        docker build -t keyglitch/go-httpbin-arm:latest -f /github/workspace/go-httpbin-arm/Dockerfile . && \
        docker tag keyglitch/go-httpbin-arm:latest keyglitch/go-httpbin-arm:$(cat /github/workspace/go-httpbin-arm/VERSION) && \
        docker push keyglitch/go-httpbin-arm
          
    - name: buildpush perkeep-arm
      run: |
        docker build -t keyglitch/perkeep-arm:latest -f /github/workspace/perkeep-arm/Dockerfile . && \
        docker tag keyglitch/perkeep-arm:latest keyglitch/perkeep-arm:$(cat /github/workspace/perkeep-arm/VERSION) && \
        docker push keyglitch/perkeep-arm
          
    - name: buildpush arm minio-arm
      run: |
        docker build -t keyglitch/minio-arm:latest -f /github/workspace/minio-arm/Dockerfile . && \
        docker tag keyglitch/minio-arm:latest keyglitch/minio-arm:$(cat /github/workspace/minio-arm/VERSION) && \
        docker push keyglitch/minio-arm
          
    - name: buildpush lego-arm
      run: |
        docker build -t keyglitch/lego-arm:latest -f /github/workspace/lego-arm/Dockerfile . && \
        docker tag keyglitch/lego-arm:latest keyglitch/lego-arm:$(cat /github/workspace/lego-arm/VERSION) && \
        docker push keyglitch/lego-arm
          
    - name: buildpush arm rest-server-arm
      run: |
        docker build -t keyglitch/rest-server-arm:latest -f /github/workspace/rest-server-arm/Dockerfile . && \
        docker tag keyglitch/rest-server-arm:latest keyglitch/rest-server-arm:$(cat /github/workspace/rest-server-arm/VERSION) && \
        docker push keyglitch/rest-server-arm
          
    - name: buildpush armv6 prometheus
      run: |
        docker build -t keyglitch/prometheus:latest -f /github/workspace/prometheus/Dockerfile . && \
        docker tag keyglitch/prometheus:latest keyglitch/prometheus:$(cat /github/workspace/prometheus/VERSION) && \
        docker push keyglitch/prometheus
          
    - name: buildpush armv6 alertmanager
      run: |
        docker build -t keyglitch/alertmanager:latest -f /github/workspace/alertmanager/Dockerfile . && \
        docker tag keyglitch/alertmanager:latest keyglitch/alertmanager:$(cat /github/workspace/alertmanager/VERSION) && \
        docker push keyglitch/alertmanager
          
    - name: buildpush armv6 blackbox_exporter
      run: |
        docker build -t keyglitch/blackbox_exporter:latest -f /github/workspace/blackbox_exporter/Dockerfile . && \
        docker tag keyglitch/blackbox_exporter:latest keyglitch/blackbox_exporter:$(cat /github/workspace/blackbox_exporter/VERSION) && \
        docker push keyglitch/blackbox_exporter
          
    - name: buildpush f3.dockerfile
      run: |
        docker build -t keyglitch/f3 -f f3/f3.dockerfile . && docker push keyglitch/f3
